### ISSUE TITLE
Please include util function to be exported e.g nfcall 

### ISSUE THREAD

**Issue by jeffreycahyono** [feathersjs-ecosystem/feathers-nedb#113]
I'm using nedb service and want to add custom methods for example adding clearAll method  like this:
```
  clearAll() {
    return nfcall(this.getModel({}), 'remove', {}, { multi: true });
  }
```
It would be helpfull if the ```nfcall``` function in util.js also exported in final lib so that the user of this library can use it to add another custom function  to nedb model.

https://github.com/feathersjs-ecosystem/feathers-nedb/blob/cd687b046bdf9eb992cf66f0efd8c321f87f4697/lib/utils.js#L13

**Comment by daffl** [comment]
This is the same thing as the now built-in [NodeJS `reqiure('utils').promisify`](https://nodejs.org/api/util.html#util_util_promisify_original).
