### ISSUE TITLE
Find request returns all entries whatever the params

### ISSUE THREAD

**Issue by arkabase** [feathersjs-ecosystem/feathers-nedb#114]
### Steps to reproduce

a NEDB data collection with 2 entries, different `type` property : 
```
{"_id":"<cardid>","type":"admin",...}
{"_id":"<cardid>","type":"customer",...}
```
a `cards` feathers service

a CURL query : 

`curl -H 'Content-Type: application/json' -X GET http://<host>/cards -d '{"type":"customer"}'`

returns all the collection entries instead of filtering with params

### Expected behavior

`{"total":1,"limit":10,"skip":0,"data":[{"_id":"<cardid>","type":"customer",...}]}`

### Actual behavior

`{"total":2,"limit":10,"skip":0,"data":[{"_id":"<cardid>","type":"admin",...},{"_id":"<cardid>","type":"customer",...}]}`

### System configuration

**Operating System**: Debian 10 Buster

**NodeJS**: 14.16.0

**feathers-nedb**: 5.1.0

**nedb**: 1.8.0

**Comment by daffl** [comment]
As documented in the [Querying API](https://docs.feathersjs.com/api/databases/querying.html#equality) you should use a query string, for HTTP `GET` requests not a JSON body:

```
curl -H 'Content-Type: application/json' -X GET http://<host>/cards?type=customer
```
