### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by nickdex** [feathersjs-ecosystem/feathers-nedb#80]
Are typescript definition files available for this, like other feathers packages?

**Comment by nickdex** [comment]
I was able to make it work (with partial type support). I am happy to help to integrate it

**Comment by daffl** [comment]
There are TypesScript definitions for both, Feathers services and the common query API on DefinitelyTyped so I don't believe this would be too difficult.

**Comment by nickdex** [comment]
Can you please share link to common query API TS definitions

**Comment by daffl** [comment]
They're all in https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by nickdex** [comment]
0 results for feathers__memory and feathers__nedb, either in DefinitelyTyped or in npm registry. Thats why I asked for a link to them

**Comment by daffl** [comment]
What I was saying that it should be fairly straightforward to create database adapter definitions (which do not exist) by using the existing ones for the [Feathers service interface](https://docs.feathersjs.com/api/services.html) and [querying API](https://docs.feathersjs.com/api/databases/querying.html).

**Comment by daffl** [comment]
The best place to discuss this would be in a new issue in https://github.com/feathersjs-ecosystem/feathers-typescript

**Comment by nickdex** [comment]
Oh okay. Thanks, will take a look at them
