### ISSUE TITLE
Update/Patch always upsert a new record

### ISSUE THREAD

**Issue by 7NT** [feathersjs-ecosystem/feathers-nedb#83]
Need help:
when I called:
app.service('users').patch(_id, { status: 0 })

or
const params = {
query: { email: user.email },
nedb: { upsert: false }
}

app.service('users').patch(null, { status: 0 }, params )

no matter server side or client, it always add a new record in my nedb database, I just want to change that status in that matched record, how can I do it?

TIA

**Comment by ayman-alkom** [comment]
I have the same problem

**Comment by ayman-alkom** [comment]
sorry it seems not a problem but this is the way that nedb works, I noticed the it remove the duplicates automatically later, and always will return the correct updated objects
